//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace AWModel
{
    public partial class SalesOrderHeaderShipping
    {
        #region Primitive Properties
    
        public virtual int SalesOrderID
        {
            get { return _salesOrderID; }
            set
            {
                if (_salesOrderID != value)
                {
                    if (SalesOrderHeader != null && SalesOrderHeader.SalesOrderID != value)
                    {
                        SalesOrderHeader = null;
                    }
                    _salesOrderID = value;
                }
            }
        }
        private int _salesOrderID;
    
        public virtual Nullable<System.DateTime> ShipDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ShipToAddressID
        {
            get;
            set;
        }
    
        public virtual string ShipMethod
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual SalesOrderHeader SalesOrderHeader
        {
            get { return _salesOrderHeader; }
            set
            {
                if (!ReferenceEquals(_salesOrderHeader, value))
                {
                    var previousValue = _salesOrderHeader;
                    _salesOrderHeader = value;
                    FixupSalesOrderHeader(previousValue);
                }
            }
        }
        private SalesOrderHeader _salesOrderHeader;

        #endregion
        #region Association Fixup
    
        private void FixupSalesOrderHeader(SalesOrderHeader previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.SalesOrderHeaderShipping, this))
            {
                previousValue.SalesOrderHeaderShipping = null;
            }
    
            if (SalesOrderHeader != null)
            {
                SalesOrderHeader.SalesOrderHeaderShipping = this;
                if (SalesOrderID != SalesOrderHeader.SalesOrderID)
                {
                    SalesOrderID = SalesOrderHeader.SalesOrderID;
                }
            }
        }

        #endregion
    }
}
