//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace AWModel
{
    public partial class SalesOrderDetail
    {
        #region Primitive Properties
    
        public virtual int SalesOrderID
        {
            get { return _salesOrderID; }
            set
            {
                if (_salesOrderID != value)
                {
                    if (SalesOrderHeader != null && SalesOrderHeader.SalesOrderID != value)
                    {
                        SalesOrderHeader = null;
                    }
                    _salesOrderID = value;
                }
            }
        }
        private int _salesOrderID;
    
        public virtual int SalesOrderDetailID
        {
            get;
            set;
        }
    
        public virtual short OrderQty
        {
            get;
            set;
        }
    
        public virtual int ProductID
        {
            get { return _productID; }
            set
            {
                if (_productID != value)
                {
                    if (Product != null && Product.ProductID != value)
                    {
                        Product = null;
                    }
                    _productID = value;
                }
            }
        }
        private int _productID;
    
        public virtual decimal UnitPrice
        {
            get;
            set;
        }
    
        public virtual decimal UnitPriceDiscount
        {
            get;
            set;
        }
    
        public virtual decimal LineTotal
        {
            get;
            set;
        }
    
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Product Product
        {
            get { return _product; }
            set
            {
                if (!ReferenceEquals(_product, value))
                {
                    var previousValue = _product;
                    _product = value;
                    FixupProduct(previousValue);
                }
            }
        }
        private Product _product;
    
        public virtual SalesOrderHeader SalesOrderHeader
        {
            get { return _salesOrderHeader; }
            set
            {
                if (!ReferenceEquals(_salesOrderHeader, value))
                {
                    var previousValue = _salesOrderHeader;
                    _salesOrderHeader = value;
                    FixupSalesOrderHeader(previousValue);
                }
            }
        }
        private SalesOrderHeader _salesOrderHeader;

        #endregion
        #region Association Fixup
    
        private void FixupProduct(Product previousValue)
        {
            if (previousValue != null && previousValue.SalesOrderDetails.Contains(this))
            {
                previousValue.SalesOrderDetails.Remove(this);
            }
    
            if (Product != null)
            {
                if (!Product.SalesOrderDetails.Contains(this))
                {
                    Product.SalesOrderDetails.Add(this);
                }
                if (ProductID != Product.ProductID)
                {
                    ProductID = Product.ProductID;
                }
            }
        }
    
        private void FixupSalesOrderHeader(SalesOrderHeader previousValue)
        {
            if (previousValue != null && previousValue.SalesOrderDetails.Contains(this))
            {
                previousValue.SalesOrderDetails.Remove(this);
            }
    
            if (SalesOrderHeader != null)
            {
                if (!SalesOrderHeader.SalesOrderDetails.Contains(this))
                {
                    SalesOrderHeader.SalesOrderDetails.Add(this);
                }
                if (SalesOrderID != SalesOrderHeader.SalesOrderID)
                {
                    SalesOrderID = SalesOrderHeader.SalesOrderID;
                }
            }
        }

        #endregion
    }
}
