//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace AWModel
{
    public partial class vProductModelCatalogDescription
    {
        #region Primitive Properties
    
        public virtual int ProductModelID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Summary
        {
            get;
            set;
        }
    
        public virtual string Manufacturer
        {
            get;
            set;
        }
    
        public virtual string Copyright
        {
            get;
            set;
        }
    
        public virtual string ProductURL
        {
            get;
            set;
        }
    
        public virtual string WarrantyPeriod
        {
            get;
            set;
        }
    
        public virtual string WarrantyDescription
        {
            get;
            set;
        }
    
        public virtual string NoOfYears
        {
            get;
            set;
        }
    
        public virtual string MaintenanceDescription
        {
            get;
            set;
        }
    
        public virtual string Wheel
        {
            get;
            set;
        }
    
        public virtual string Saddle
        {
            get;
            set;
        }
    
        public virtual string Pedal
        {
            get;
            set;
        }
    
        public virtual string BikeFrame
        {
            get;
            set;
        }
    
        public virtual string Crankset
        {
            get;
            set;
        }
    
        public virtual string PictureAngle
        {
            get;
            set;
        }
    
        public virtual string PictureSize
        {
            get;
            set;
        }
    
        public virtual string ProductPhotoID
        {
            get;
            set;
        }
    
        public virtual string Material
        {
            get;
            set;
        }
    
        public virtual string Color
        {
            get;
            set;
        }
    
        public virtual string ProductLine
        {
            get;
            set;
        }
    
        public virtual string Style
        {
            get;
            set;
        }
    
        public virtual string RiderExperience
        {
            get;
            set;
        }
    
        public virtual System.Guid rowguid
        {
            get;
            set;
        }
    
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion
    }
}
