//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace AWModel
{
    public partial class ProductModel
    {
        #region Primitive Properties
    
        public virtual int ProductModelID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string CatalogDescription
        {
            get;
            set;
        }
    
        public virtual System.Guid rowguid
        {
            get;
            set;
        }
    
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Product> Products
        {
            get
            {
                if (_products == null)
                {
                    var newCollection = new FixupCollection<Product>();
                    newCollection.CollectionChanged += FixupProducts;
                    _products = newCollection;
                }
                return _products;
            }
            set
            {
                if (!ReferenceEquals(_products, value))
                {
                    var previousValue = _products as FixupCollection<Product>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProducts;
                    }
                    _products = value;
                    var newValue = value as FixupCollection<Product>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProducts;
                    }
                }
            }
        }
        private ICollection<Product> _products;
    
        public virtual ICollection<ProductModelProductDescription> ProductModelProductDescriptions
        {
            get
            {
                if (_productModelProductDescriptions == null)
                {
                    var newCollection = new FixupCollection<ProductModelProductDescription>();
                    newCollection.CollectionChanged += FixupProductModelProductDescriptions;
                    _productModelProductDescriptions = newCollection;
                }
                return _productModelProductDescriptions;
            }
            set
            {
                if (!ReferenceEquals(_productModelProductDescriptions, value))
                {
                    var previousValue = _productModelProductDescriptions as FixupCollection<ProductModelProductDescription>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProductModelProductDescriptions;
                    }
                    _productModelProductDescriptions = value;
                    var newValue = value as FixupCollection<ProductModelProductDescription>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProductModelProductDescriptions;
                    }
                }
            }
        }
        private ICollection<ProductModelProductDescription> _productModelProductDescriptions;

        #endregion
        #region Association Fixup
    
        private void FixupProducts(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Product item in e.NewItems)
                {
                    item.ProductModel = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Product item in e.OldItems)
                {
                    if (ReferenceEquals(item.ProductModel, this))
                    {
                        item.ProductModel = null;
                    }
                }
            }
        }
    
        private void FixupProductModelProductDescriptions(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ProductModelProductDescription item in e.NewItems)
                {
                    item.ProductModel = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProductModelProductDescription item in e.OldItems)
                {
                    if (ReferenceEquals(item.ProductModel, this))
                    {
                        item.ProductModel = null;
                    }
                }
            }
        }

        #endregion
    }
}
