//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace AWModel
{
    public partial class vGetAllCategory
    {
        #region Primitive Properties
    
        public virtual string ParentProductCategoryName
        {
            get;
            set;
        }
    
        public virtual string ProductCategoryName
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ProductCategoryID
        {
            get;
            set;
        }

        #endregion
    }
}
