USE [CodeGenerator]
GO

/****** Object:  Table [dbo].[CGEN_DataTypes]    Script Date: 08/03/2012 02:42:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CGEN_DataTypes](
	[DataTypeName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CGEN_DataTypes_1] PRIMARY KEY CLUSTERED 
(
	[DataTypeName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


